### ISSUE TITLE
Simplify CSS code for all shared properties.

### ISSUE THREAD

**Issue by josephtkim** [KarenS4/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code as much as possible to make the code cleaner and to remove repetitive code. Like you did for shared properties in the html tag, also apply for the other shared properties among multiple selectors. Here is how you might simplify the code further, for the font-weight property,

```css
h1, h2, .bold, h3 {
  font-weight: bold;
}
```
